### PR TITLE
Implementing hashcode, equals, getters on Param, adding test coverage, testability

### PR DESCRIPTION
**Pull request by jameskbride**
Hi Walker,

I wanted to suggest a few changes for consistency and testing purposes.  
1. Implementing hashcode, equals on Param
2. Adding getters to Param for accessibility, testing
3. Adding additional test coverage (for these changes)
4. Making a number of protected methods public for accessibility

I introduced these in my own fork a couple of months ago and I've been using them since with no problems.  My primary reason for doing so was to be able to test around the library.  Let me know what you think and get back to me when you can.

Thanks!

### CODE REVIEW

**Comment by jameskbride** [comment]
Checked the build, it is due to the integration test that requires the API key to be in place to pass.

**Comment by jameskbride** [comment]
Hi @windy1, apologies for a half-baked pull request.  Regarding the first part from a few days ago see the notes above.  The second part allows an arbitrary API url to be passed in, with the hopes that we could make a server-side call to Google Places from a client without exposing the API key in the params. To secure the call to the server though we would need to have some other security mechanism in place, such as OAuth2, etc.  

Let me know what you think about the security aspects of this project.  In the meantime I'm going to close this pull request.  

Thanks.

**Comment by windy1** [comment]
@jameskbride Honestly, I'm not too concerned about security in this library.

**Comment by jameskbride** [comment]
My major concern is that currently only the server API keys work with Google Places.  Generating an Android key is the first thing I did, and the API rejects it out of hand.  That being said, from a security standpoint we are exposing the API key on every request.  It wouldn't take much for someone to sniff the network and grab the API key for their own use.  I'd prefer to be able to use a solution such as what I described above (server-side call with the client passing parameters sans-API key coupled with an OAuth mechanism). 

To make this library compatible with the security requirements (at least for a solution such as what I just described) we'd need to be able to override the API url currently being used with a url of our choice.  

I love what this library does in terms of parsing, serialization/deserialization, but I don't particularly like the hard-coded API url and the security holes it opens.  

Anyway, think it over.  I know you're probably busy, but I'd like to at least have a conversation about this functionality.  

Thanks,

Jim

**Pull request closed without merging**
