### PR TITLE
Fix issue #21.

### PR DESCRIPTION
**Pull request by 0x3333**
Allow radar searches to return 200 maximum results, as specified in the API: 

https://developers.google.com/places/web-service/search#RadarSearchRequests

### CODE REVIEW

**Comment by 0x3333** [comment]
I added different methods to get and parse radar query.

I changed the public method `parse` to constraint the `limit` parameter, as it is public, and removed it from `parseResults` method, as it is private and the input is already sanitized.

**Comment by windy1** [comment]
Nice! Have you run the tests on this?

**Comment by 0x3333** [comment]
I did, but the travis is not setting the API Key... thats why it is failing...

**Comment by 0x3333** [comment]
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running se.walkercrou.places.GooglePlacesTest
******************** getNearbyPlacesRankedByDistance ********************
Page: 1
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.923 sec <<< FAILURE!
testGetNearbyPlacesRankedByDistance(se.walkercrou.places.GooglePlacesTest)  Time elapsed: 0.844 sec  <<< ERROR!
se.walkercrou.places.exception.GooglePlacesException: java.lang.IllegalArgumentException: Illegal character in query at index 66: https://maps.googleapis.com/maps/api/place/nearbysearch/json?key=${env.GOOGLE_PLACES_API_KEY}&location=44.478025,-73.196475&radius=50000.000000
```

**Comment by 0x3333** [comment]
```
...Illegal character in query at index 66: https://maps.googleapis.com/maps/api/place/nearbysearch/json?key=${env.GOOGLE_PLACES_API_KEY}...
```

**Comment by windy1** [comment]
Yeah, I'm aware of that with travis, I just wanted to make sure you had run it locally. Thanks!

**Pull request merged**
